version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: yarn start
    container_name: frontend
    image: frontend_base
    ports:
      - "3000:3000"
    volumes:
      - ./:/frontend
      - /frontend/node_modules
